### PR TITLE
[wip] Added material icons

### PR DESCRIPTION
**Pull request by meetdilip**
Removed Roboto !important to make sure it does not clash with the font choice.

### CODE REVIEW

**Comment by meetdilip** [comment]
Any idea why CSS is not loaded ?

**Comment by ardacebi** [comment]
Because I applied your PR to the forum. Let me change it back.

**Comment by meetdilip** [comment]
Not like that. That line should not block CSS from loading. Please feel free to change.

**Comment by ardacebi** [comment]
OK, it should be done now.

Btw, yes, that line caused the css to not load. Try it yourself on a localhost Flarum.

**Comment by meetdilip** [comment]
I do not have Flarum on localhost. Will see what I can do.

**Comment by ardacebi** [comment]
Sign up to the demo forum and I'll give you admin access.

**Comment by meetdilip** [comment]
Late night here. Will do tomorrow

**Comment by ardacebi** [comment]
@meetdilip Can you see #62?

It's working, live on the demo forum: https://flightsimtr.tk

**Pull request closed without merging**
