### PR TITLE
Dropdown Button Fix

### PR DESCRIPTION
**Pull request by ghost**
This will fix a bug that deals with a Right Margin missing so some buttons do NOT connect to others.

### CODE REVIEW

**Review by ardacebi — COMMENTED** [review]
What does this fix visually? I tried but this didn't change anything. Screenshots, maybe?

**Comment by ghost** [comment]
screenshot 172
This gives buttons space between each other.

**Comment by ardacebi** [comment]
Can you send me a before & after screenshots? Because I still don't see anything in visual.

**Comment by ghost** [comment]
screenshot 173
This is before, the other is after.

**Comment by ardacebi** [comment]
This fix also messes up the discussion list: https://flightsimtr.tk/

**Comment by ghost** [comment]
I will find a fix.

**Comment by ardacebi** [comment]
Please include your fix in the `fixes` branch so it will be included in this PR.

After you apply the fix, ping me here so I'll review it again.

**Comment by ghost** [comment]
I think I did something but, that should fix it.

**Pull request merged**
