### PR TITLE
Fix for Admin/Permissions page

### LINKED ISSUE #15: Fix for permissions/admin page
screenshot_2018-07-23 flightsimtr - havacilik forumu 1

This page looks messed up 😬

### PR DESCRIPTION
**Pull request by ghost**
Fixes #15

**Changes**

This will fix the Admin Permission Page Button bug, now Compatible with Mobile and Desktop.

**Reviewers should focus on**

`Check` code.

**Screenshots**

None.

**Additional Information**

None.

### CODE REVIEW

**Review by ardacebi — CHANGES_REQUESTED** [review]
Seems like it doesn't work:

screenshot_2018-07-27 extum material theme demo 3

I don't know about Chrome though, that screenshot is from Firefox.

**Comment by ghost** [comment]
Not everything is gonna be Compatible with every browser, most use Chrome.

**Comment by ardacebi** [comment]
Funny thing is it's the same on Chrome:



Probably because of .less

**Review by ardacebi — CHANGES_REQUESTED** [review]
The exact same. (Firefox)

screenshot_2018-07-27 extum material theme demo 4

**Comment by ghost** [comment]
This one will finally fix it.
screenshot 233

That's live on the site already, so you can test it.

**Review by ardacebi — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
