### PR TITLE
Fix for the square loader issue on notification settings

### LINKED ISSUE #66: Loader issue on notification settings
**Describe the bug**
The temporary loader resulted in an issue at the notification settings table that it appears something square.

**To Reproduce**
1. Go to settings
2. Click on one of the notification settings from the table
3. See error

**Expected behavior**
The standard temporary loader should appear. (Click on a switch below to see the standard temporary loader.)

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Url: https://materialtheme.freeflarum.com/
 - Flarum Version: 0.1.0-beta.7

### PR DESCRIPTION
**Pull request by Wolfuryo**
Fixes #66

Make the loader round and smaller on the notifications settings

### CODE REVIEW

**Review by ardacebi — CHANGES_REQUESTED** [review]
Can you decrease the loader width a bit for it to look thinner? Not so much, it should be the same as the one on the guidelines (or the one on other screens)

**Comment by Wolfuryo** [comment]
Do you mean decreasing the width on the notifications settings or everywhere?

**Comment by ardacebi** [comment]
On the notification settings.

The loader everywhere is already OK, do it like that.

**Review by ardacebi — APPROVED** [review]
This looks OK for now, thank you.

**Pull request merged**
