### PR TITLE
Two fixes [Critical]

### PR DESCRIPTION
**Pull request by hammerhai**
See changes in files and pull requests from Forked repository.

### CODE REVIEW

**Comment by hammerhai** [comment]
Halt this PR until further notice due to an occurance.

**Comment by hammerhai** [comment]
Sorry something happened there after I organized the LESS and CSS, didn't notice until I refreshed on my end 😅

**Comment by MeteorCoder** [comment]
This is sad 😂 I don't remember how to properly use GitHub, it's been so long

**Comment by ardacebi** [comment]
> Halt this PR until further notice due to an occurance.

@MeteorCoder ??

**Comment by hammerhai** [comment]
You're good for take off @ardacebi

**Comment by hammerhai** [comment]
@ardacebi 19 days later 😂

**Review by ardacebi — CHANGES_REQUESTED** [review]
What does bundle.less do here? It didn't use to exist as I remember 🤔

**Comment by hammerhai** [comment]
It makes it so all CSS is together in one file instead of switching back and fourth to add it to Flarum in case you can't install the extension... for example FreeFlarum.

**Pull request merged**
