### PR TITLE
Fixes Profile Menu Icons Alignment

### PR DESCRIPTION
**Pull request by ghost**
**Changes**

Fixes Profile Menu icon alignment. (Mobile & Desktop)

**Reviewers should focus on**

https://github.com/Extum/flarum-ext-material/blob/586f6d26cfeef9dd2425b1e193ec64f13c10c74d/material.less#L269-L274

**Screenshots**

Before:
None.

After:
screenshot 223

**Additional Information**

None.

### CODE REVIEW

**Comment by ardacebi** [comment]
Please add a before screenshot.

**Review by ardacebi — APPROVED** [review]
LGTM.

**Comment by ghost** [comment]
Please re-open this, this issue is also present elsewhere, see the below image:
image

**Comment by ghost** [comment]
NVM, i'll open a new pr

**Comment by ardacebi** [comment]
@PartialDevAdmin I'm waiting for your PR.

**Comment by ghost** [comment]
It seems that the fix I applied, doesn't work. Doesn't even work on my Community, IDK why when I added the correct things. @PartialDevAdmin I'll look into what I can do for that problem as well.

**Pull request merged**
