### PR TITLE
[wip] Login button text centering added

### PR DESCRIPTION
**Pull request by meetdilip**
Padding corrected

### CODE REVIEW

**Review by ardacebi — COMMENTED** [review]
Seems like I get the same result with this too. Nothing changes for no reason.

**Comment by ghost** [comment]
I'll check this issue.

**Comment by ghost** [comment]
Nvm... Is this for the Login Button on desktop or Mobile?

**Comment by ghost** [comment]
Whoops, I just noticed it too while fixing other bugs, I'll see if I can fix.

**Comment by ardacebi** [comment]
@Nathan2023 Anything about this?

**Pull request closed without merging**
